GET http://localhost:4000/api/v1/getallusers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2Mjk5MzM4M2U5YzA5MGZiZWJjZGM1MDIiLCJxdW90ZXMiOltdLCJlbWFpbCI6ImQiLCJwYXNzd29yZCI6IiQyYSQxMiRxLk5jU1ZmTzcxbUpiZXQ4ZnM0dWNlNXBuWlJCeVk3WHpHUy8vRXhjUGNuMzZaaHI5VHlpTyIsInJvbGUiOiJhZG1pbiIsInVzZXJJcyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjU0MjA3NTc0LCJleHAiOjE2NTQyMTQ3NzR9.ZbuUJbM4aSwL0BRapeCthn4bChOq4RRuvAeiaOD2u6c

###
post http://localhost:4000/api/v1/signup
Content-Type: application/json

{
    "email": "admin", 
    "password": "d", 
    "confirmPassword": "d", 
    "role":"admin"
}
###


###
post http://localhost:4000/api/v1/login
Content-Type: application/json

{
    "email":"a@gmail.com",
    "password":"aaaaaa"
} 

###
###
put http://localhost:4000/api/v1/updateprofile/62993383e9c090fbebcdc502
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2Mjk5MzM4M2U5YzA5MGZiZWJjZGM1MDIiLCJxdW90ZXMiOltdLCJlbWFpbCI6ImQiLCJwYXNzd29yZCI6IiQyYSQxMiRxLk5jU1ZmTzcxbUpiZXQ4ZnM0dWNlNXBuWlJCeVk3WHpHUy8vRXhjUGNuMzZaaHI5VHlpTyIsInJvbGUiOiJhZG1pbiIsInVzZXJJcyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjU0MjA3NTc0LCJleHAiOjE2NTQyMTQ3NzR9.ZbuUJbM4aSwL0BRapeCthn4bChOq4RRuvAeiaOD2u6c
Content-Type: application/json

{
    "email":"soliana@gmail.com"
}  
###
delete http://localhost:4000/api/v1/deleteprofile/62993383e9c090fbebcdc502
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2Mjk5MzM4M2U5YzA5MGZiZWJjZGM1MDIiLCJxdW90ZXMiOltdLCJlbWFpbCI6ImQiLCJwYXNzd29yZCI6IiQyYSQxMiRxLk5jU1ZmTzcxbUpiZXQ4ZnM0dWNlNXBuWlJCeVk3WHpHUy8vRXhjUGNuMzZaaHI5VHlpTyIsInJvbGUiOiJhZG1pbiIsInVzZXJJcyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjU0MjA3NTc0LCJleHAiOjE2NTQyMTQ3NzR9.ZbuUJbM4aSwL0BRapeCthn4bChOq4RRuvAeiaOD2u6c
###
get http://localhost:4000/api/v1/quote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2MjlhNzdhMDMxNTM5ZWFmZWFjYjI4ZjQiLCJxdW90ZXMiOlsiNjI5YjIzODgyZTlkZGU5ZDMwMDlhM2UyIiwiNjI5YjIzZWQyZTlkZGU5ZDMwMDlhM2VjIiwiNjI5YjI2MmUyZTlkZGU5ZDMwMDlhNDBlIl0sImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkMFJPUDI3aGpKazlDUnF5VFp3UUJxLllFOS5KUjN3a3lNOTNxWHExcDE4bnBEcjBzR29YZi4iLCJyb2xlIjoiYWRtaW4iLCJ1c2VySXMiOiJBZG1pbiIsIl9fdiI6MTl9LCJpYXQiOjE2NTQzMzkyNjQsImV4cCI6MTY1NDM0NjQ2NH0.VROzY3Mo0lezWXrih5MOAKuEOziZduIctA9jB7I9EYM

###
get http://localhost:4000/api/v1/quote/629936d23fa6d795c1107a08
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2Mjk5MzM4M2U5YzA5MGZiZWJjZGM1MDIiLCJxdW90ZXMiOltdLCJlbWFpbCI6ImQiLCJwYXNzd29yZCI6IiQyYSQxMiRxLk5jU1ZmTzcxbUpiZXQ4ZnM0dWNlNXBuWlJCeVk3WHpHUy8vRXhjUGNuMzZaaHI5VHlpTyIsInJvbGUiOiJhZG1pbiIsInVzZXJJcyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjU0MjA3NTc0LCJleHAiOjE2NTQyMTQ3NzR9.ZbuUJbM4aSwL0BRapeCthn4bChOq4RRuvAeiaOD2u6c

###
post http://localhost:4000/api/v1/quote/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2MjlhNzdhMDMxNTM5ZWFmZWFjYjI4ZjQiLCJxdW90ZXMiOlsiNjI5YjIzODgyZTlkZGU5ZDMwMDlhM2UyIiwiNjI5YjIzZWQyZTlkZGU5ZDMwMDlhM2VjIiwiNjI5YjI2MmUyZTlkZGU5ZDMwMDlhNDBlIl0sImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkMFJPUDI3aGpKazlDUnF5VFp3UUJxLllFOS5KUjN3a3lNOTNxWHExcDE4bnBEcjBzR29YZi4iLCJyb2xlIjoiYWRtaW4iLCJ1c2VySXMiOiJBZG1pbiIsIl9fdiI6MTl9LCJpYXQiOjE2NTQzMzkyNjQsImV4cCI6MTY1NDM0NjQ2NH0.VROzY3Mo0lezWXrih5MOAKuEOziZduIctA9jB7I9EYM
Content-Type: application/json

{
    "category":"category 1",
    "author":"alayu",
    "body":"fafa"
}
###
put http://localhost:4000/api/v1/quote/629b36ffce06393901966b1f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2MjlhNzdhMDMxNTM5ZWFmZWFjYjI4ZjQiLCJxdW90ZXMiOlsiNjI5YjIzODgyZTlkZGU5ZDMwMDlhM2UyIiwiNjI5YjIzZWQyZTlkZGU5ZDMwMDlhM2VjIiwiNjI5YjI2MmUyZTlkZGU5ZDMwMDlhNDBlIl0sImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkMFJPUDI3aGpKazlDUnF5VFp3UUJxLllFOS5KUjN3a3lNOTNxWHExcDE4bnBEcjBzR29YZi4iLCJyb2xlIjoiYWRtaW4iLCJ1c2VySXMiOiJBZG1pbiIsIl9fdiI6MTl9LCJpYXQiOjE2NTQzMzkyNjQsImV4cCI6MTY1NDM0NjQ2NH0.VROzY3Mo0lezWXrih5MOAKuEOziZduIctA9jB7I9EYM
Content-Type: application/json

{
    "category":"category 4"
}
###
delete http://localhost:4000/api/v1/quote/629936fdc1c1c85b88cb9041
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2Mjk5MzM4M2U5YzA5MGZiZWJjZGM1MDIiLCJxdW90ZXMiOltdLCJlbWFpbCI6ImQiLCJwYXNzd29yZCI6IiQyYSQxMiRxLk5jU1ZmTzcxbUpiZXQ4ZnM0dWNlNXBuWlJCeVk3WHpHUy8vRXhjUGNuMzZaaHI5VHlpTyIsInJvbGUiOiJhZG1pbiIsInVzZXJJcyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjU0MjA3NTc0LCJleHAiOjE2NTQyMTQ3NzR9.ZbuUJbM4aSwL0BRapeCthn4bChOq4RRuvAeiaOD2u6c

###
post http://localhost:4000/api/v1/quote/favorite/629933a5e9c090fbebcdc50a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2Mjk5MzM4M2U5YzA5MGZiZWJjZGM1MDIiLCJxdW90ZXMiOltdLCJlbWFpbCI6ImQiLCJwYXNzd29yZCI6IiQyYSQxMiRxLk5jU1ZmTzcxbUpiZXQ4ZnM0dWNlNXBuWlJCeVk3WHpHUy8vRXhjUGNuMzZaaHI5VHlpTyIsInJvbGUiOiJhZG1pbiIsInVzZXJJcyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjU0MjA3NTc0LCJleHAiOjE2NTQyMTQ3NzR9.ZbuUJbM4aSwL0BRapeCthn4bChOq4RRuvAeiaOD2u6c
Content-Type: application/json

{
    "quoteId":"629937180769066e251452ae"
}
###

delete http://localhost:4000/api/v1/quote/favorite/629933a5e9c090fbebcdc50a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2Mjk5MzM4M2U5YzA5MGZiZWJjZGM1MDIiLCJxdW90ZXMiOltdLCJlbWFpbCI6ImQiLCJwYXNzd29yZCI6IiQyYSQxMiRxLk5jU1ZmTzcxbUpiZXQ4ZnM0dWNlNXBuWlJCeVk3WHpHUy8vRXhjUGNuMzZaaHI5VHlpTyIsInJvbGUiOiJhZG1pbiIsInVzZXJJcyI6IkFkbWluIiwiX192IjowfSwiaWF0IjoxNjU0MjA3NTc0LCJleHAiOjE2NTQyMTQ3NzR9.ZbuUJbM4aSwL0BRapeCthn4bChOq4RRuvAeiaOD2u6c
Content-Type: application/json

{
    "quoteId":"629937180769066e251452ae"
}

###
get http://localhost:4000/api/v1/quote/favorite/629bbd57212cc7b4b27e1ba6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2MjliYmQ1NzIxMmNjN2I0YjI3ZTFiYTYiLCJmYXZvcml0ZXMiOlsiNjI5YmJkYWUyMTJjYzdiNGIyN2UxYmMzIiwiNjI5YmJkYWUyMTJjYzdiNGIyN2UxYmMzIl0sImVtYWlsIjoiYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMiRyL3VsVlFYL2lHRzhmb1ZrUFdaQnJ1b293LzZtMWg4Q2UzaG5CN1hORXNTQWtKaC5RY0Z0TyIsInJvbGUiOiJhcHB1c2VyIiwidXNlcklzIjoiQXBwVVNlciIsIl9fdiI6Mn0sImlhdCI6MTY1NDM3NTE4MywiZXhwIjoxNjU0MzgyMzgzfQ.SaNhNiNauXxGCKLQ25H1slEeXzQ0wb9aj8-Oown9WmU


###
delete http://localhost:4000/api/v1/quote/favorite/629bbd57212cc7b4b27e1ba6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXJyZW50VXNlciI6eyJfaWQiOiI2MjliYmQ1NzIxMmNjN2I0YjI3ZTFiYTYiLCJmYXZvcml0ZXMiOlsiNjI5YmJkYWUyMTJjYzdiNGIyN2UxYmMzIiwiNjI5YmJkYWUyMTJjYzdiNGIyN2UxYmMzIl0sImVtYWlsIjoiYUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYSQxMiRyL3VsVlFYL2lHRzhmb1ZrUFdaQnJ1b293LzZtMWg4Q2UzaG5CN1hORXNTQWtKaC5RY0Z0TyIsInJvbGUiOiJhcHB1c2VyIiwidXNlcklzIjoiQXBwVVNlciIsIl9fdiI6Mn0sImlhdCI6MTY1NDM3NTE4MywiZXhwIjoxNjU0MzgyMzgzfQ.SaNhNiNauXxGCKLQ25H1slEeXzQ0wb9aj8-Oown9WmU
Content-Type: application/json

{
    "quoteId":"629bbd9d212cc7b4b27e1bb7"
}